rvm: 2.1.3
before_install:
  - rvm get stable
install:
  - bundle install --jobs=3 --retry=3 --deployment
  - bundle exec pod install
notifications:
  email: false
osx_image: xcode7
language: objective-c
script:
- xctool -workspace Slam.xcworkspace -scheme Slam -sdk iphonesimulator9.0 clean build test -freshInstall -freshSimulator
