before_install:
  - bundle
before_script: security delete-certificate -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/System.keychain; security delete-certificate -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/login.keychain; curl -O -L http://developer.apple.com/certificationauthority/AppleWWDRCA.cer; security import AppleWWDRCA.cer  -k ~/Library/Keychains/login.keychain -A
language: objective-c
notifications:
  email: false
osx_image: xcode8
script: xcodebuild -workspace Slam.xcworkspace -scheme Slam -sdk iphonesimulator10.0 -destination 'platform=iOS Simulator,name=iPhone 6' build test